# Generated by Django 4.0 on 2022-01-15 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(max_length=20, null=True)),
                ('format', models.CharField(max_length=20, null=True)),
                ('contact', models.CharField(max_length=20, null=True)),
                ('message', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20, null=True)),
                ('to_read_list', models.TextField(null=True)),
                ('library', models.TextField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Read',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(max_length=20, null=True)),
                ('to_read', models.BooleanField(null=True)),
                ('finished', models.BooleanField(null=True)),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='book_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(max_length=20, null=True)),
                ('message', models.TextField(null=True)),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='book_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN', models.CharField(max_length=20, null=True)),
                ('name', models.CharField(max_length=40, null=True)),
                ('cover', models.ImageField(upload_to=None)),
                ('author', models.CharField(max_length=20, null=True)),
                ('genre', models.CharField(max_length=20, null=True)),
                ('summary', models.TextField(null=True)),
                ('discussion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='book_app.discussion')),
                ('read', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='book_app.read')),
                ('trade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='book_app.add_books')),
            ],
        ),
        migrations.AddField(
            model_name='add_books',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='book_app.user'),
        ),
    ]
