# Generated by Django 4.0 on 2022-01-20 13:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.AddField(
            model_name='discussion',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='read',
            name='finished',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='read',
            name='to_read',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
