# Generated by Django 4.0 on 2022-01-20 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('book_app', '0002_remove_user_email_remove_user_password_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Book_User',
        ),
    ]
