# Generated by Django 4.0 on 2022-02-05 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0003_rename_user_book_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_user',
            name='library',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book_user',
            name='to_read_list',
            field=models.TextField(blank=True, null=True),
        ),
    ]
