# Generated by Django 4.0 on 2022-02-25 06:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0004_alter_book_user_library_alter_book_user_to_read_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_user',
            name='bio',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='book_user',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/users'),
            preserve_default=False,
        ),
    ]
