# Generated by Django 4.0.4 on 2022-04-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0005_book_user_bio_book_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_user',
            name='image',
            field=models.ImageField(default='images/default/roman.png', upload_to='images/users'),
        ),
    ]
