# Generated by Django 4.0.4 on 2022-04-22 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0006_alter_book_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_user',
            name='image',
            field=models.ImageField(default='images/default/rto.pdf', upload_to='images/users'),
        ),
    ]
