# Generated by Django 4.0 on 2022-05-02 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0007_alter_book_user_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Books',
        ),
    ]
