# Generated by Django 4.0 on 2022-05-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0008_delete_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_user',
            name='bio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book_user',
            name='image',
            field=models.ImageField(default='images/default/roman.png', upload_to='images/users'),
        ),
    ]
