# Generated by Django 4.0 on 2022-05-02 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0009_alter_book_user_bio_alter_book_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_user',
            name='image',
            field=models.ImageField(default='images/default/depositphotos_72350117-stock-illustration-no-user-profile-picture-hand.jpg', upload_to='images/users'),
        ),
    ]
