# Generated by Django 4.0 on 2022-05-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0010_alter_book_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_user',
            name='followers',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book_user',
            name='following',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book_user',
            name='image',
            field=models.ImageField(default='images/default/tux.png', upload_to='images/users'),
        ),
    ]
